### ISSUE TITLE
Cron timing

### ISSUE THREAD

**Issue by sharpchi** [hugoacfs/tailor-feed#11]
Have a think about cron timing for different feed types. e.g. Twitter posts get updated frequently, but RSS much less so.
Perhaps each feed class can define how often to run, perhaps we need to record when a particular feed cron was run.
We can still have one cron.php, but this will respond to the individual feeds.

**Comment by hugoacfs** [comment]
Configuration was added to deal with this, feature update will cover this issue and issue #12

**Comment by hugoacfs** [comment]
New DB structure enables this.
