### ISSUE TITLE
Duplicate modal html

### ISSUE THREAD

**Issue by sharpchi** [hugoacfs/tailor-feed#52]
The html in modal-topics.php, modal-pages.php and modal.php are all identical except for the name of some classes and ids.
Would it be possible to create a function that produces the output depending on the type of modal being request? e.g. print_modal($type);
This way you wouldn't need to do a require for each file, and you wouldn't need to update each one if you make a change, or need to create a new one for a new type.
You could do a single require_once as part of your loading routing in config.php

**Comment by hugoacfs** [comment]
Added builder function

**Comment by sharpchi** [comment]
This function would be used by timeline.php.
It might a good idea to return a string from the function, rather than directly echoing out, you can then leave it up to the output page to echo it where it wants.

**Comment by hugoacfs** [comment]
Amended function
