### ISSUE TITLE
Timeline doesn't list pages if there are no topics

### ISSUE THREAD

**Issue by sharpchi** [hugoacfs/tailor-feed#7]
1. Ensure the topics and articles_topics and subscribed_articles tables are empty.
2. Subscribe the default user to one source
3. Run the cron
4. Check the cron has populated articles
4. The timeline displays no articles

**Comment by sharpchi** [comment]
Error is in fetchUserSubscribedArticles() and you're adding a where on topic status, even when there are no topics.
```php
WHERE `s`.`status` = 'active' AND `t`.`status` = 'active' AND (";
```
The solution will be to conditionally add the where status checks if there is at least one topic or source.

**Comment by hugoacfs** [comment]
Fixed and merged, updated the query to make pages and topics independent from each other
